#!/usr/bin/python

import glob
env = Environment(CPPPATH = ['Include', '../libELL/Include'])

env.Library('ellxml', glob.glob('Source/*'))
env.Program('xml_test', 'Test/Test.cpp', LIBS = 'ellxml', LIBPATH = '.')
